version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: buttdialer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    
  backend:
    build: ./buttdialer/backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/buttdialer
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./buttdialer/backend:/app
    
  frontend:
    build: ./buttdialer/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./buttdialer/frontend:/app

volumes:
  postgres_data: